# 光栅化渲染器配置文件 - 复杂测试配置
# test_complex_config.toml

[files]
obj = "obj/models/spot/spot_triangulated.obj"
output = "complex_test_render"
output_dir = "test_output"
texture = "obj/models/spot/spot_texture.png"  # 可选：如果有纹理文件
background_image = "obj/models/spot/hmap.jpg"  # 可选：如果有背景图片

[render]
width = 1920
height = 1080
projection = "perspective"
use_zbuffer = true
colorize = false
use_texture = true
use_gamma = true
enable_aces = false
backface_culling = true
wireframe = false
cull_small_triangles = true
min_triangle_area = 0.001
save_depth = true

[camera]
from = "2.5,1.5,4.0"
at = "0,0.5,0"
up = "0,1,0"
fov = 60.0

[object]
position = "0,0.2,0"
rotation = "15,30,0"
scale_xyz = "1.2,1.0,1.2"
scale = 1.5

[lighting]
use_lighting = true
ambient = 0.2
ambient_color = "0.2,0.3,0.4"

# 多光源配置 - 方向光 + 两个点光源
[[light]]
type = "directional"
enabled = true
direction = "0.3,-0.8,-0.5"
color = "1.0,0.95,0.8"
intensity = 0.8

[[light]]
type = "point"
enabled = true
position = "2.0,3.0,2.0"
color = "1.0,0.8,0.6"
intensity = 2.5
constant_attenuation = 1.0
linear_attenuation = 0.09
quadratic_attenuation = 0.032

[[light]]
type = "point"
enabled = true
position = "-1.5,2.0,1.0"
color = "0.6,0.8,1.0"
intensity = 1.8
constant_attenuation = 1.0
linear_attenuation = 0.14
quadratic_attenuation = 0.07

[material]
use_phong = false  # 修改：改为使用PBR渲染
use_pbr = true

# === 通用材质属性 ===
alpha = 0.75

# === Phong材质参数 ===
diffuse_color = "0.7,0.5,0.3"
diffuse_intensity = 1.2      # 新增：漫反射强度
specular_color = "0.9,0.8,0.7"  # 修复：改为颜色格式
specular_intensity = 0.8     # 新增：镜面反射强度
shininess = 64.0

# === 扩展的PBR材质参数 ===
base_color = "0.85,0.7,0.6"
metallic = 0.0              # 非金属
roughness = 0.6             # 中等粗糙度
ambient_occlusion = 0.8
emissive = "0.0,0.0,0.0"


[shadow]
# === 阴影映射 (地面阴影) ===
enable_shadow_mapping = true
shadow_map_size = 2048
shadow_bias = 0.001
shadow_distance = 20.0
enable_pcf = true
pcf_type = "Box"
pcf_kernel = 2
pcf_sigma = 1.0

[background]
use_background_image = true
enable_gradient_background = true
gradient_top_color = "0.3,0.5,0.8"
gradient_bottom_color = "0.8,0.6,0.4"
enable_ground_plane = true
ground_plane_color = "0.4,0.6,0.3"
ground_plane_height = -0.5

[animation]
animate = false
fps = 60
rotation_speed = 0.8
rotation_cycles = 2.0
animation_type = "CameraOrbit"
rotation_axis = "Custom"
custom_rotation_axis = "0.2,1,0.3"